import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Router, { useRouter } from 'next/router'
import { FormattedMessage, useIntl } from 'react-intl'
import Link from 'next/link'
import SiteHeader from '@/components/siteheader'

export default function Home({dir}) {

  const { locales } = useRouter(); 
  const intl = useIntl();
  const title = intl.formatMessage({ id: "page.home.head.title"})
  const description = intl.formatMessage({ id: "page.home.head.meta.description"})
  const nav = intl.formatMessage({ id: "page.home.head.navbar"})
  
  return (
    <>
      <Head>
        <title>Digital Design and Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BCIT_logo.png" />
        <link rel="icon" href="/BCIT_logo.png" hrefLang='x-default'/>
        <link rel="icon" href="/BCIT_logo.png" hrefLang='en'/>
        <link rel="icon" href="/BCIT_logo.png" hrefLang='fr'/>
        <link
          url="https://geogrotesquecyr-medium-webfont.woff2"
          rel="stylesheet"
        />
        <link
          url="https://geogrotesquecyr-medium-webfont.woff"
          rel="stylesheet"
        />
        <link
          url="https://mabrypro-light-webfont.woff2"
          rel="stylesheet"
        />
        <link
          url="https://mabrypro-light-webfont.woff"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet"></link>
      </Head>

      <main dir={dir} className={styles.main}>
        {/* <h1>
          <FormattedMessage
          id="page.home.head.title"
          values={{b: (info) => <b>{info}</b>}}
          />
          </h1>
          <p>
          <FormattedMessage
          id="page.home.head.description"
          />
        </p> */}
        <div className={styles.mainContainer}>
          <div className={styles.siteHeaderContainer}>
            <div className={styles.siteHeader}>
              <header className={styles.header}>
                {[...locales].sort().map((locale) => (
                  <Link key={locale} href="/" locale={locale}>
                    <div>{locale}</div>
                  </Link>
                ))}
              </header>
              <a>
                <FormattedMessage
                  id="page.home.head.navbar.learnhub"            
                />
              </a>  
              <a>
                <FormattedMessage
                  id="page.home.head.navbar.mybcit"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.head.navbar.staff"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.head.navbar.students"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.head.navbar.events"
                />
              </a>
            </div>
          </div>
          <div className={styles.menuContainer}>
            <div className={styles.menuNav}>
              <Image className={styles.logo} src="/BCIT_logo.png"
                alt="BCIT logo"
                width={69.63}
                height={69.63}
              />
              <a>
                <FormattedMessage
                  id="page.home.menu.program"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.menu.admission"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.menu.studentservice"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.menu.research"
                />
              </a>
              <a>
                <FormattedMessage
                  id="page.home.menu.about"
                />
              </a>
            </div> 
            <i className={styles.fa_search}
                  width={100}
                  height={100}
                  alt="srch btn"
                />
            <div className={styles.menuSearchContainer}>
              <div className={styles.menuSearch}>
                <input className={styles.searchInput}
                  type="text"
                />
              </div>
            </div>
          </div>
          <div className={styles.breadcrumbsContainer}>
            <div className={styles.breadcrumbs}>
              <a>
                <FormattedMessage
                  id="page.home.breadcrumbs.study"
                />
              </a>
              <div className={styles.triangle}></div>
              <a>
                <FormattedMessage
                  id="page.home.breadcrumbs.b&m"
                />
              </a>
              <div className={styles.triangle}></div>
              <a>
                <FormattedMessage
                  id="page.home.head.title"
                />
              </a>
            </div>
          </div>
          <div className={styles.bannerContainer}>
            <Image
              className={styles.mainImage}
              src="/main-image.jpeg"
              width={1424}
              height={465}
              alt="main image"
            />
            <div className={styles.bannerContent}>
              <div className={styles.bannerLeft}>
                <h1 className={styles.mainTitle}>
                  <FormattedMessage
                    id="page.home.head.title"
                  />
                </h1>
                <div className={styles.bannerTextContent}>
                  <p>
                    <FormattedMessage
                      id="page.home.hero.meta.diploma"
                    />
                  </p>
                  <p>/</p>
                  <p>
                    <FormattedMessage
                      id="page.home.hero.meta.fulltime"
                    />
                  </p>
                  <p>/</p>
                  <p>
                    <FormattedMessage
                      id="page.home.hero.meta.sb&m"
                    />
                  </p>
                </div>
                <div className={styles.iconContainer}>
                  <i class="fa fa-print"></i>
                  <i class='fa fa-envelope'></i>
                  <i class='fa fa-facebook-f'></i>
                  <i class='fa fa-twitter'></i>
                </div>
              </div>
              <div className={styles.bannerRight}>
                <div className={styles.buttonContainer}>
                  <button className={styles.contactButton}>
                    <FormattedMessage
                      id="page.home.banner.button.apply"
                    />
                    <i class="fa fa-angle-right"></i>
                  </button>
                  <button className={styles.contactButton}>
                    <FormattedMessage
                      id="page.home.banner.button.contact"
                    />
                    <i class="fa fa-angle-right"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.sideNavBarContainer}>
            <div className={styles.sideNavBar}>
              <h3 className={styles.sideNavTitle}>
                <FormattedMessage
                  id="page.home.sidenav.aboutprogram"
                />
              </h3>
              <div className={styles.navOverview}>
                <ul className={styles.navOverviewList}>
                  <li className={styles.brightBlueText}>
                    <FormattedMessage
                      id="page.home.sidenav.overview"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.entrancerequirements"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.advancedplacement"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.costandsupplies"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.programdetails"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.graduating"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.contact"
                    />
                  </li>
                  <li className={styles.sideNavCategories}>
                    <FormattedMessage
                      id="page.home.sidenav.subscribe"
                    />
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.programInfoContainer}>
              <div className={styles.programInfo}>
                <h3 className={styles.sideNavTitle}>
                  <FormattedMessage
                    id="page.home.info.sessions"
                  />
                </h3>
                <p className={styles.infoSessionDesc}>
                  <FormattedMessage
                    id="page.home.info.sessions.message"
                  />
                </p>
                <ul>
                  <li className={styles.infoDates}>
                    <FormattedMessage
                      id="page.home.info.date.april"
                    />
                  </li>
                  <li className={styles.infoDates}>
                    <FormattedMessage
                      id="page.home.info.date.may"
                    />
                  </li>
                  <li className={styles.infoDates}>
                    <FormattedMessage
                      id="page.home.info.date.june"
                    />
                  </li>
                  <li className={styles.infoDates}>
                    <FormattedMessage
                      id="page.home.info.date.july"
                    />
                  </li>
                </ul>
                <div className={styles.infoExploreDesc}>
                  <p>
                   <FormattedMessage
                    id="page.home.info.explore"
                    /> 
                  </p>
                  <p className={styles.brightBlueText}>
                    <FormattedMessage
                      id="page.home.info.explore.bcit"
                    />
                  </p>
                </div>
              </div>
              <div className={styles.programOverviewContainer}>
                <div className={styles.programOverview}>
                  <div>
                    <h3 className={styles.sideNavTitle}>
                      <FormattedMessage
                        id="page.home.info.programoverview"
                      />
                    </h3>
                    <div className={styles.programOverviewCategory}>
                      <p>
                        <FormattedMessage
                          id="page.home.info.credential"
                        />
                      </p>
                      <p>
                        <FormattedMessage
                          id="page.home.info.credential.diploma"
                        />
                      </p>
                    </div>
                    <div className={styles.programOverviewCategory}>
                      <p>
                        <FormattedMessage
                          id="page.home.info.format"
                        />
                      </p>
                      <p>
                        <FormattedMessage
                          id="page.home.info.format.full-time"
                        />
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
